x = int(input('Write a number for multiplication table: '))
print('-'*15)
print(x, (f'x {1:2} = {x*1}'))
print(x, (f'x {2:2} = {x*2}'))
print(x, (f'x {3:2} = {x*3}'))
print(x, (f'x {4:2} = {x*4}'))
print(x, (f'x {5:2} = {x*5}'))
print(x, (f'x {6:2} = {x*6}'))
print(x, (f'x {7:2} = {x*7}'))
print(x, (f'x {8:2} = {x*8}'))
print(x, (f'x {9:2} = {x*9}'))
print(x, (f'x {10:2} = {x*10}'))
print('-'*15)
#print(f'{x0}\n{x1}\n{x2}\n{x3}\n{x4}\n{x5}\n{x6}\n{x6}\n{x7}\n{x8}\n{x9}')

